### ISSUE TITLE
How to add slug for terminal

### ISSUE THREAD

**Issue by TideDra** [Textualize/textual-web#35]
The URL for terminal seems always randomly generated, even if I add slug in the configuration file like this:
```toml
[account]
api_key = "xxxx"

[terminal.Terminal]
slug = "a100server"
name = "a100server"
terminal = true
```
After I run `textual-web --config ganglion.toml`, I get a url like "https://textual-web.io/MyAccount/3gu25v1b4t3h", and slug seems not work.
I wonder how to get a constant URL for terminal service?
